Task_1_1_1
Alexey-shishkin4/OOP pull request #1
Opened 2024-09-09 13:45 UTC by Alexey-shishkin4

2024-09-09 16:05 UTC, Sharapov-Maksim requested changes
Правки выдал, исправляйте, комментируйте, запрашивайте повторное ревью

2024-09-09 16:05 UTC, Sharapov-Maksim commented on Task_1_1_1/src/main/java/org/example/HeapSort.java
> +     * @param arr The array representing the heap.
`checkstyle` ругается на отсутствие пустой строки перед `@param`

2024-09-09 16:05 UTC, Sharapov-Maksim commented on Task_1_1_1/src/test/java/HeapSortTest.java
> +public class HeapSortTest {
Сделать javadoc

2024-09-09 16:05 UTC, Sharapov-Maksim commented on Task_1_1_1/j.sh
> +SRC_DIR="src"
Так попадает и класс тестов, а нужно только основные исходники обработать

2024-09-09 16:05 UTC, Sharapov-Maksim commented on Task_1_1_1/j.sh
> +SRC_DIR="src"
Из-за этого, как минимум, появляются проблемы с воспроизведением скрипта `j.sh`
```
$ ./j.sh
Компиляция исходных файлов...
src/test/java/HeapSortTest.java:3: error: package org.junit.jupiter.api does not exist
import org.junit.jupiter.api.Test;
                            ^
src/test/java/HeapSortTest.java:4: error: package org.junit.jupiter.api does not exist
import static org.junit.jupiter.api.Assertions.assertArrayEquals;
                                   ^
src/test/java/HeapSortTest.java:4: error: static import only from classes and interfaces
import static org.junit.jupiter.api.Assertions.assertArrayEquals;
^
src/test/java/HeapSortTest.java:8: error: cannot find symbol
    @Test
     ^
  symbol:   class Test
  location: class HeapSortTest
src/test/java/HeapSortTest.java:17: error: cannot find symbol
    @Test
     ^
  symbol:   class Test
  location: class HeapSortTest
src/test/java/HeapSortTest.java:26: error: cannot find symbol
    @Test
     ^
  symbol:   class Test
  location: class HeapSortTest
src/test/java/HeapSortTest.java:35: error: cannot find symbol
    @Test
     ^
  symbol:   class Test
  location: class HeapSortTest
src/test/java/HeapSortTest.java:44: error: cannot find symbol
    @Test
     ^
  symbol:   class Test
  location: class HeapSortTest
src/test/java/HeapSortTest.java:53: error: cannot find symbol
    @Test
     ^
  symbol:   class Test
  location: class HeapSortTest
src/test/java/HeapSortTest.java:14: error: cannot find symbol
        assertArrayEquals(expectedArray, inputArray, "The array should be sorted in ascending order.");
        ^
  symbol:   method assertArrayEquals(int[],int[],String)
  location: class HeapSortTest
src/test/java/HeapSortTest.java:23: error: cannot find symbol
        assertArrayEquals(expectedArray, inputArray, "The already sorted array should remain sorted.");
        ^
  symbol:   method assertArrayEquals(int[],int[],String)
  location: class HeapSortTest
src/test/java/HeapSortTest.java:32: error: cannot find symbol
        assertArrayEquals(expectedArray, inputArray, "The reverse sorted array should be sorted in ascending order.");
        ^
  symbol:   method assertArrayEquals(int[],int[],String)
  location: class HeapSortTest
src/test/java/HeapSortTest.java:41: error: cannot find symbol
        assertArrayEquals(expectedArray, inputArray, "A single-element array should remain unchanged.");
        ^
  symbol:   method assertArrayEquals(int[],int[],String)
  location: class HeapSortTest
src/test/java/HeapSortTest.java:50: error: cannot find symbol
        assertArrayEquals(expectedArray, inputArray, "An empty array should remain unchanged.");
        ^
  symbol:   method assertArrayEquals(int[],int[],String)
  location: class HeapSortTest
src/test/java/HeapSortTest.java:59: error: cannot find symbol
        assertArrayEquals(expectedArray, inputArray, "The array with duplicates should be sorted correctly.");
        ^
  symbol:   method assertArrayEquals(int[],int[],String)
  location: class HeapSortTest
15 errors
Генерация документации Javadoc...
Loading source file src/test/java/HeapSortTest.java...
Loading source file src/main/java/org/example/HeapSort.java...
Constructing Javadoc information...
src/test/java/HeapSortTest.java:3: error: package org.junit.jupiter.api does not exist
import org.junit.jupiter.api.Test;
                            ^
src/test/java/HeapSortTest.java:4: error: package org.junit.jupiter.api does not exist
import static org.junit.jupiter.api.Assertions.assertArrayEquals;
                                   ^
src/test/java/HeapSortTest.java:4: error: static import only from classes and interfaces
import static org.junit.jupiter.api.Assertions.assertArrayEquals;
^
src/test/java/HeapSortTest.java:8: error: cannot find symbol
    @Test
     ^
  symbol:   class Test
  location: class HeapSortTest
src/test/java/HeapSortTest.java:17: error: cannot find symbol
    @Test
     ^
  symbol:   class Test
  location: class HeapSortTest
src/test/java/HeapSortTest.java:26: error: cannot find symbol
    @Test
     ^
  symbol:   class Test
  location: class HeapSortTest
src/test/java/HeapSortTest.java:35: error: cannot find symbol
    @Test
     ^
  symbol:   class Test
  location: class HeapSortTest
src/test/java/HeapSortTest.java:44: error: cannot find symbol
    @Test
     ^
  symbol:   class Test
  location: class HeapSortTest
src/test/java/HeapSortTest.java:53: error: cannot find symbol
    @Test
     ^
  symbol:   class Test
  location: class HeapSortTest
9 errors
Создание JAR-файла...
added manifest
Запуск приложения...
Error: Could not find or load main class org.example.HeapSort
Caused by: java.lang.ClassNotFoundException: org.example.HeapSort
```

2024-09-09 16:05 UTC, Sharapov-Maksim commented on Task_1_1_1/src/test/java/HeapSortTest.java
> +        assertArrayEquals(expectedArray, inputArray, "The array should be sorted in ascending order.");
Можно разбивать выражение на строчки, чтобы `checkstyle` не ругался.
Например, так:
```
assertArrayEquals(expectedArray, inputArray, 
    "The array should be sorted in ascending order.");
```
Насчёт точного оформления лучше посмотреть в Google Java Code Style. Ну или замечания чекера поправить потом =)

2024-09-09 16:05 UTC, Sharapov-Maksim commented on Task_1_1_1/src/main/java/org/example/HeapSort.java
> +            arr[i] = temp;
Шаблон кода похож на аналогичный на строках 43-45. Стоит вынести в отдельную функцию `swap`

2024-09-10 05:40 UTC, Alexey-shishkin4 commented on Task_1_1_1/src/main/java/org/example/HeapSort.java
> +     * @param arr The array representing the heap.
Исправил

2024-09-10 05:40 UTC, Alexey-shishkin4 commented on Task_1_1_1/src/test/java/HeapSortTest.java
> +public class HeapSortTest {
Исправил

2024-09-10 05:40 UTC, Alexey-shishkin4 commented on Task_1_1_1/j.sh
> +SRC_DIR="src"
Переделал

2024-09-10 05:40 UTC, Alexey-shishkin4 commented on Task_1_1_1/src/test/java/HeapSortTest.java
> +        assertArrayEquals(expectedArray, inputArray, "The array should be sorted in ascending order.");
Исправил

2024-09-10 05:41 UTC, Alexey-shishkin4 commented on Task_1_1_1/src/main/java/org/example/HeapSort.java
> +            arr[i] = temp;
Исправил

2024-09-10 05:41 UTC, Alexey-shishkin4 commented
Правки внес

2024-09-10 10:50 UTC, Sharapov-Maksim commented
Для запроса повторного ревью у вас должна быть кнопка в интерфейсе PR, не забывайте её прожимать

2024-09-10 11:05 UTC, Sharapov-Maksim commented on Task_1_1_1/j.sh
> +SRC_DIR="src"
А запускали?

```
$ ./j.sh
error: file not found: src/main/java/org.example/HeapSort.java
Usage: javac <options> <source files>
use --help for a list of possible options
error: File not found: "src/main/java/org.example/HeapSort.java"
1 error
Error: Could not find or load main class org.example.HeapSort
Caused by: java.lang.ClassNotFoundException: org.example.HeapSort
```

Думаю переменная `SRC` как-то неправильно задана...

2024-09-10 11:08 UTC, Sharapov-Maksim requested changes

2024-09-10 11:08 UTC, Sharapov-Maksim commented on Task_1_1_1/j.sh
> +java -classpath gradleless org.example.HeapSort
А `java` нечего запускать. `main` метод нужен

2024-09-10 12:34 UTC, Alexey-shishkin4 commented on Task_1_1_1/j.sh
> +java -classpath gradleless org.example.HeapSort
добавил main метод

2024-09-10 13:44 UTC, Alexey-shishkin4 commented
Добавил метод main

2024-09-10 13:45 UTC, Sharapov-Maksim commented on Task_1_1_1/src/main/java/org/example/HeapSort.java
> +    static void printArray(int[] arr) {
На будущее: можно было просто позвать `Arrays.toString`

2024-09-10 13:48 UTC, Sharapov-Maksim commented
Жду исправления [последнего замечания](https://github.com/Alexey-shishkin4/OOP/pull/1#discussion_r1751743590)

2024-09-10 14:14 UTC, Alexey-shishkin4 commented
Изменил скрипт

2024-09-10 15:22 UTC, Sharapov-Maksim approved these changes

2024-09-10 15:23 UTC, merged