Task_1_2_2
Alexey-shishkin4/OOP pull request #4
Opened 2024-10-14 15:07 UTC by Alexey-shishkin4

2024-10-18 04:58 UTC, Sharapov-Maksim requested changes
Мягкий дедлайн зачтён, исправляйте замечания

2024-10-18 04:58 UTC, Sharapov-Maksim commented on Task_1_2_2/src/main/java/org/example/Main.java
> +// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
?

2024-10-18 04:58 UTC, Sharapov-Maksim commented on Task_1_2_2/src/main/java/org/example/HashTable.java
> +    }
По своему контракту (см. `java.lang.Object#hashcode()`) метод `hashcode` должен обладать следующим свойством:
> If two objects are equal according to the equals(Object) method, then calling the hashCode method on each of the two objects must produce the same integer result.

В вашей реализации выглядит так, что `result` зависит от порядка итерации по таблице. Порядок итерации у вас не фиксирован. Две хеш-таблицы, в которые в разном порядке клали одинаковые элементы будут равны по `equals`, но могут дать разный `hashcode`.

**В качестве решения можно просто складывать хеш-коды элементов без умножения. Но перед тем, как это сделать, нужно будет сделать тест, который бы падал с вашей текущей реализацией и перестал бы падать после исправления**

2024-10-18 04:58 UTC, Sharapov-Maksim commented on Task_1_2_2/src/main/java/org/example/HashTable.java
> +    }
Давайте у этого метода либо поменяем семантику, чтобы была проверка на наличие в таблице `key`, либо удалим метод, чтобы избежать дублирования

2024-10-22 14:40 UTC, Alexey-shishkin4 commented
правки внес

2024-10-22 15:41 UTC, Sharapov-Maksim commented on Task_1_2_2/src/main/java/org/example/HashTable.java
> +    }
Ну вот, а сложный тест на hashcode не сделали

2024-10-22 15:45 UTC, Sharapov-Maksim requested changes

2024-10-22 15:45 UTC, Sharapov-Maksim commented on Task_1_2_2/src/main/java/org/example/HashTable.java
> +        }
javadoc надо тоже обновить

2024-10-25 18:01 UTC, Alexey-shishkin4 commented
javadoc обновил

2024-10-26 12:03 UTC, Sharapov-Maksim commented
Вы не забывайте перезапрашивать ревью

2024-10-26 12:04 UTC, Sharapov-Maksim commented
Задание зачтено, PR можно мёржить

2024-10-26 12:04 UTC, Sharapov-Maksim approved these changes

2024-11-03 09:01 UTC, merged