Task_1_3_1
Alexey-shishkin4/OOP pull request #5
Opened 2024-11-03 09:08 UTC by Alexey-shishkin4

2024-11-03 15:31 UTC, Sharapov-Maksim requested changes
Мягкий дедлайн зачтён

2024-11-03 15:31 UTC, Sharapov-Maksim commented on Task_1_3_1/src/main/java/org/example/SubstringSearch.java
> +                while ((index = buffer.indexOf(searchString)) != -1) {
`indexOf` надо самому реализовать, лабораторная же про это

2024-11-03 15:31 UTC, Sharapov-Maksim commented on Task_1_3_1/src/test/java/SubstringSearchTest.java
> +class SubstringSearchTest {
Давайте добавим тестов с кравыми случаями: поиск в пустой строке, поиск строки из одного символа

2024-11-03 15:31 UTC, Sharapov-Maksim commented on Task_1_3_1/src/test/java/SubstringSearchTest.java
> +class SubstringSearchTest {
> размер входного файла может быть во много раз больше объема оперативной памяти вычислительного устройства, а размер искомой подстроки — во много раз меньше;

Давайте подобный тест добавите, где файл в несколько раз больше свободной памяти под кучу. 
И попробуйте провести эксперимент: запустить данный тест с ограниченным размером кучи (см. -Xmx VM option, например: `-Xmx256m` для файла в 1GB), проверить, что он не падает с OutOfMemory. При этом стоит сделать тест так, чтобы не раздувать список `occurences`, желательно чтобы найденное вхождение было одно или их не было вовсе. Об условиях и результатах эксперимента напишите комментарий =)

2024-11-06 16:24 UTC, Alexey-shishkin4 commented on Task_1_3_1/src/main/java/org/example/SubstringSearch.java
> +                while ((index = buffer.indexOf(searchString)) != -1) {
исправил

2024-11-06 16:26 UTC, Alexey-shishkin4 commented on Task_1_3_1/src/test/java/SubstringSearchTest.java
> +class SubstringSearchTest {
добавил

2024-11-06 16:37 UTC, Alexey-shishkin4 commented on Task_1_3_1/src/test/java/SubstringSearchTest.java
> +class SubstringSearchTest {
менял размер хипа для тестов в build.gradle 
tasks.named('test', Test) {
    useJUnitPlatform()

    maxHeapSize = '256m'

    testLogging {
        events "passed"
    }
}

Особых изменений не заметил при выполнение теста, ошибки не было, может только грузил на пару секунд дольше, чем при хипе в 1G

2024-11-06 16:40 UTC, Alexey-shishkin4 commented
Правки внес

2024-11-08 18:02 UTC, Sharapov-Maksim approved these changes
Задание зачтено, PR можно мёржить

2024-11-17 14:39 UTC, merged